### ISSUE TITLE
Package textures, etc, within the singular FBX output.

### ISSUE THREAD

**Issue by Visavant** [Arbos/nwn2mdk#2]
Can you provide a console parameter to support combining all related assets to the model to sit within the final FBX output file from the NWN2 MDB/MDL conversion? This would help prevent nomenclature collision with batch conversions, or is the data structure too disparate between software suites for this to work?

**Comment by Arbos** [comment]
If a texture already exists in the destination, **nw2fbx** doesn't extracts it from NWN2_Materials*.zip, so there can't be name collision. This serves you?

**Comment by Visavant** [comment]
That works, thank you.
