### ISSUE TITLE
FBX Ascii

### ISSUE THREAD

**Issue by Visavant** [Arbos/nwn2mdk#3]
Is there a param you could provide that allows FBX output in ascii mode?

**Comment by Arbos** [comment]
What's your use case for needing the generated FBX to be ascii?

**Comment by Visavant** [comment]
Future application support, some applications also don't support binary version yet unless there's an existing binary to ascii fbx conversion tool out there without purchase?

**Comment by Arbos** [comment]
Currently **nw2fbx** generates binary FBX version 7.4. This version is needed for importing into Blender and I have been reported that it works wih 3ds Max 2016 and 3ds Max 2018. If there is some application that is useful for NWN2 modding and that doesn't import this FBX, then I would consider adding an option to specify the FBX output format.
