### ISSUE TITLE
nw2fbx crash

### ISSUE THREAD

**Issue by kaszapatrik** [Arbos/nwn2mdk#4]
I tried to export an animation from GR2 file, but nw2fbx crashed. My GR2 file is not from Neverwinter, but from Metin2. In Metin2 have two type of GR2 files - one for model and skeleton, and one for animation.

The model+skeleton file is success to export FBX (and I can import to Blender, so it's works).
The animation file crashed.
You have any idea for that?

The log file and the animation gr2:
[files.zip](https://github.com/Arbos/nwn2mdk/files/1839746/files.zip)

**Comment by Arbos** [comment]
I have inspected the GR2 animation. It's from an older version of Granny 3D than the one used by NWN2 and the format is different. My tools are to work with NWN2 only, and I have no intention in making a generic GR2 converter. Whatever works with GR2 files from other games is a matter of luck.
