### ISSUE TITLE
Building from source issue

### ISSUE THREAD

**Issue by jayn23** [Arbos/nwn2mdk#6]
Hi Arbos,

Firstly great tool, very cool!!
I am having trouble building from your source code, and was wondering if you could write some basic tutorial, my main issues are with the yaml_cpp, which i guess i am doing something wrong.

What i did was download yaml source from "https://github.com/jbeder/yaml-cpp/tree/master/include/yaml-cpp" used cmake to generate a build then added "yaml-cpp.vcxproj" as a project. since the build didnt have the include/ymal-cpp/ directory i tried refrencing it but that didnt work.

Another issue is when targeting FBX SDK as long as i targeted existing path that was set by you it worked, but when i tried targeting SDK 2018 1.1 or 2019 it faild with error "cannot open libfbxsdk.lib"  is there another definition i need to set in order to target another SDK version?

Sorry if these are basics, i am more of a python guy, but i want to use you tool to study GR2 format and get better with C++

Thanks in advance

**Comment by jayn23** [comment]
So by deleting everything except for "nwn2mdk-lib" and "dumpgr2" i got it working, for my purpose of gr2 research its more than enough, thanks again for the great tool!

**Comment by bottledspace** [comment]
I would like to reopen this as I'm running into the same issues and build instructions would be greatly appreciated!
