### ISSUE TITLE
Error upon importing mdb

### ISSUE THREAD

**Issue by DolbitNihuya** [Arbos/nwn2mdk#9]
I have an issue that no one bothered to probably report until now;
Why do you need a file nwn2mdk-tmp.fbx that isn't even provided in github??

Importing .mdb causes this error:

Python: Traceback (most recent call last):
File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\nwn2mdk_init_.py", line 189, in execute
bpy.ops.import_scene.fbx(filepath=tmpfbx,
File "G:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in call
ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Couldn't open file 'C:\Users\user\Downloads\te\nwn2mdk-tmp.fbx' ([Errno 2] No such file or directory: 'C:\Users\user\Downloads\te\nwn2mdk-tmp.fbx')

Trust me, I tried using older blender versions, it's the same.

**Comment by Arbos** [comment]
nwn2mdk-tmp.fbx is a temporary file created by the add-on.

It seems there was something happening before the reported error. Look if there is a file a file called C:\Users\user\Downloads\te\log.txt.

**Comment by DolbitNihuya** [comment]
Importing with Blender 4.0.2/NWN2 MDK 0.17

ERROR: Cannot find a NWN2 installation directory. Edit the config.yml file and put the directory where NWN2 is installed.

**Comment by DolbitNihuya** [comment]
What is there to edit in config.yml file?

**Comment by Arbos** [comment]
The add-on requires NWN2 to be installed. If you have installed NWN2, I would expect the add-on to automatically find the installation folder, unless there is some edge case that I'm not aware of.

In any case, you can specify the NWN2 installation folder in config.yml, which is located where the add-on is installed. By looking at your error message, it should be in C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\nwn2mdk. The config.yml file has comments that explains how to edit it, hopefully.

**Comment by DolbitNihuya** [comment]
Thanks, will look into it.

**Comment by DolbitNihuya** [comment]
log: 
Importing with Blender 4.0.2/NWN2 MDK 0.17

ERROR: Cannot find a NWN2 installation directory. Edit the config.yml file and put the directory where NWN2 is installed.




Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\nwn2mdk\__init__.py", line 189, in execute
    bpy.ops.import_scene.fbx(filepath=tmpfbx,
  File "G:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Couldn't open file "C:\\Users\\Users\\Downloads\\foldermodels\\foldermodels\\originalfiles\\nwn2mdk-tmp.fbx" ([Errno 2] No such file or directory: "C:\\Users\\user\\Downloads\\foldermodels\\foldermodels\\originalfiles\\nwn2mdk-tmp.fbx")


my config:

# Intructions
# ===========
#
# Comments start with hashtag (#).
#
# Optional properties are commented by default. Remove the hashtag at the
# start of the line to use the property.
#
# A property has the following syntax:
#
#   property_name: value
#

# (Optional) Directory where NWN2 is installed.
# nwn2_home: G:\SteamLibrary\steamapps\common\Neverwinter Nights 2

**Comment by DolbitNihuya** [comment]
Had to remove the "#" for  "nwn2_home:" from the config.yml and it worked.
